#pragma once
#include "Core/Application.h"
#include "Core/Core.h"
#include "Core/EventDispatcher.h"
#include "Core/GL.h"
#include "Core/Input.h"
#include "Core/Timer.h"
#include "Core/Window.h"

#include "Geometry/Geometry.h"
#include "Geometry/Mesh.h"
#include "Geometry/MeshFactory.h"
#include "Geometry/MeshUtils.h"
#include "Geometry/Model.h"

#include "Math/Math.h"

#include "Misc/Colour.h"

#include "Render/Shader.h"
#include "Render/Texture.h"

#include "Scene/Component/Camera.h"
#include "Scene/Component/Geometry.h"
#include "Scene/Component/Light.h"
#include "Scene/Component/Material.h"
#include "Scene/Component/NameTag.h"
#include "Scene/Component/Transform.h"
#include "Scene/Common.h"
#include "Scene/Entity.h"
#include "Scene/EntityManager.h"
#include "Scene/Scene.h"
#include "Scene/System.h"
#include "Scene/System/CameraSystem.h"
#include "Scene/System/CoreSystem.h"
